version: '3.9'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: teste
  api:
    image: akka-api:1.0
    tty: true
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PASS: teste
      ENVIRONMENT: prod